language: r
sudo: false
cache: packages

r_packages: 
  - Formula
  - SparseM
  - MatrixModels
  - nlme
  - lme4
  - pbkrtest
  - quantreg
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
