language: r

r_packages: 
  - AER
  - plm
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
  
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
