language: r
cache: packages

r_packages: 
  - covr
  - nlme
  - plm
  
after_success:
  - Rscript -e 'covr::codecov()'
  
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
