language: r

before_install:
  - sudo rm -fvr /home/travis/R-bin/lib/R/library/nlme
  - Rscript -e 'install.packages("nlme", lib="/home/travis/R-bin/lib/R/library/")'
  
r_packages: 
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
