language: r
sudo: false
cache: packages

r_packages: 
  - Formula
  - nlme
  - SparseM
  - MatrixModels
  - lme4
  - pbkrtest
  - quantreg
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e '.libPaths(); sapply(.libPaths(),packageVersion,pkg="nlme")'
  
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
